Repository google/latexify_py, pull requests merged in 2022-11, with the labels that each got.

#72 More and more refactoring.
  checks.sh
  src/integration_tests/regression_test.py
  src/latexify/codegen/__init__.py
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
  src/latexify/constants.py
  src/latexify/frontend.py
  src/latexify/frontend_test.py
  src/latexify/node_visitor_base.py
  src/latexify/node_visitor_base_test.py
  src/latexify/test_utils.py
  src/latexify/transformers/__init__.py
  src/latexify/transformers/assignment_reducer.py
  src/latexify/transformers/assignment_reducer_test.py
Labels: bug: minor, refactoring

#73 Add latexify.function/expression frontends
  examples/examples.ipynb
  src/integration_tests/regression_test.py
  src/latexify/__init__.py
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
  src/latexify/frontend.py
  src/latexify/frontend_test.py
Labels: feature

#77 Support multi-clause comprehension in sum and prod.
  src/latexify/analyzers_test.py
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#80 fix: sub operate cause bracket error
  src/integration_tests/regression_test.py
  src/latexify/codegen/function_codegen.py
Labels: bug: major

#92 Entire refactoring of BinOp/UnaryOp/Compare/BoolOp
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature, refactoring

#95 Release scripts
  .github/workflows/release.yml
  pyproject.toml
  src/latexify/__init__.py
Labels: refactoring, release

#94 Support set operations.
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
  src/latexify/frontend.py
  src/latexify/frontend_test.py
Labels: feature

#98 add documentation.
  README.md
  docs/getting_started.md
  docs/index.md
  docs/parameters.md
Labels: documentation

#99 ci: Upgrade GitHub Actions and Python
  .github/workflows/ci.yml
  pyproject.toml
Labels: refactoring

#112 Fix brackets display
  src/integration_tests/regression_test.py
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#111 Add support for ast.IfExp
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#121 Add utility to process LaTeX expressions
  src/latexify/codegen/latex.py
  src/latexify/codegen/latex_test.py
Labels: refactoring

#133 Move `expand_functions` to `Config`
  src/latexify/config.py
  src/latexify/frontend.py
Labels: refactoring

#139 IdentifierConverter
  docs/getting_started.md
  docs/parameters.md
  pyproject.toml
  src/integration_tests/regression_test.py
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
  src/latexify/codegen/identifier_converter.py
  src/latexify/codegen/identifier_converter_test.py
  src/latexify/config.py
  src/latexify/frontend.py
  src/latexify/frontend_test.py
  src/latexify/math_symbols.py
  src/latexify/math_symbols_test.py
Labels: feature, refactoring
