Repository google/latexify_py, pull requests merged in 2022-12, with the labels that each got.

#143 NDArray support
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#144 Adds parse_expr utility
  src/latexify/analyzers_test.py
  src/latexify/ast_utils.py
  src/latexify/ast_utils_test.py
  src/latexify/codegen/function_codegen_test.py
Labels: refactoring

#150 Fix bug and remove unnecessary brackets.
  docs/getting_started.md
  docs/parameters.md
  src/integration_tests/function_expansion_test.py
  src/integration_tests/regression_test.py
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
  src/latexify/constants.py
  src/latexify/frontend_test.py
Labels: bug: minor, refactoring

#151 Revert BuiltinFnName
  src/latexify/constants.py
  src/latexify/transformers/function_expander.py
Labels: refactoring

#148 Special array representation
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#146 Match, match_case, and MatchValue
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#147 MatchAs
  src/latexify/codegen/function_codegen.py
  src/latexify/codegen/function_codegen_match_test.py
  src/latexify/codegen/function_codegen_test.py
Labels: feature

#166 remove common prefixes.
  src/latexify/frontend.py
  src/latexify/frontend_test.py
Labels: refactoring

#161 Change default multiplication behavior
  src/integration_tests/algorithmic_style_test.py
  src/integration_tests/regression_test.py
  src/latexify/codegen/expression_codegen_test.py
  src/latexify/codegen/expression_rules.py
  src/latexify/codegen/function_codegen_match_test.py
  src/latexify/frontend_test.py
Labels: feature

#170 publish algorithmic decorator
  src/latexify/__init__.py
Labels: refactoring

#171 Remove EXPRESSION style
  src/latexify/frontend.py
  src/latexify/generate_latex.py
Labels: refactoring

#172 Fix function name bug on algorithmic
  src/latexify/codegen/algorithmic_codegen.py
  src/latexify/codegen/algorithmic_codegen_test.py
  src/latexify/codegen/identifier_converter.py
  src/latexify/codegen/identifier_converter_test.py
Labels: bug: minor
